Good_items_base{
    "minecraft:iron_block",
    "minecraft:gold_block",
    "minecraft:enchantment_table",
    "minecraft:white_shulker_box",
    "minecraft:orange_shulker_box",
    "minecraft:magenta_shulker_box",
    "minecraft:light_blue_shulker_box",
    "minecraft:yellow_shulker_box",
    "minecraft:lime_shulker_box",
    "minecraft:pink_shulker_box",
    "minecraft:gray_shulker_box",
    "minecraft:light_gray_shulker_box",
    "minecraft:cian_shulker_box",
    "minecraft:purple_shulker_box",
    "minecraft:blue_shulker_box",
    "minecraft:brown_shulker_box",
    "minecraft:green_shulker_box",
    "minecraft:red_shulker_box",
    "minecraft:black_shulker_box",
    "minecraft:diamond",
    "minecraft:emerald",
    "minecraft:lapis",
    "minecraft:coal_block",
    "minecraft:diamond_block",
    "minecraft:emerald_block",
    "minecraft:lapis_block",
    "minecraft:obsidian",
    "minecraft:beacon",
    "minecraft:golden_apple",
    "minecraft:ender_pearl",
    "minecraft:nether_star",
    "minecraft:enchanted_book",
    "minecraft:name_tag",
    "minecraft:totem_of_undying"
}

Average_items_base{
    "minecraft:iron_ore",
    "minecraft:gold_ore",
    "minecraft:brewing_stand",
    "minecraft:book",
    "minecraft:end_rod",
    "minecraft:coal",
    "minecraft:diamond",
    "minecraft:emerald",
    "minecraft:lapis",
    "minecraft:saddle",
    "minecraft:experience_bottle",
    "minecraft:name_tag",
    "minecraft:totem_of_undying"
}

Bad_items_base{
	"minecraft:stone"
}